
== read 操作

=== 读操作发送格式
[source,json]
----
{
    "read":{
        "addr":2, 
        "len": 2  
    }
}
----
<1> addr为必要参数，范围0~14 超出范围则返回错误
<2> len为可选参数，如果没有len或len<=0时，默认len=1，长度超出寄存器地址空间不会报错，会返回实际读到的个数。可用于批量一次获得所有配置。

=== 返回
[source,json]
----
{
    "read":{
        "result":5,
    }
}
----
<1> result，返回值，类型int，为0表示完全正确，为正数时表示成功读到的个数，负数表示执行错误，参考错误码表


|=======
|执行成功     |0 
|json语法错误 |-10000   
|缺少必要参数  |-10001      
|地址参数超出范围  | -10002
|数值超出范围  | -10003
|键值对的键不存在 | -10004
|键值对的值类型不对  | -10005
|=======


== write 操作
=== 单个写作发送格式
[source,json]
----
{
    "write":{
        "addr":3,
        "value": 255
    }
}
----



=== 批量写作发送格式
[source,json]
----
{
    "write":{
        "addr":3,
        "value": [1,2,3,4,5,255,4096,65535]
    }
}
----
<1> addr为写操作的目标地址，必要参数，类型int，寄存器地址范围0~62 超出范围返回错误
<2> value为写入的值，必要参数，类型int，范围0~0xFFFF （即 0~65535）
<3> value有两种格式，当类型为int时，表示只写一个值；当类型为数组是，为批量写，以addr为首地址，以此写入数组中的值，地址自动累加

=== 返回
[source,json]
----
{
    "write":{
        "result":5,
    }
}
----
<1> result，返回值，类型int，为0表示完全正确，为正数时表示成功写入的个数，负数表示执行错误，参考错误码表

== setbits 操作

该操作可只写寄存器的部分位，以适应只想设置寄存器中的部分字段，而保持其他字段不变的情况，避免了先要读取当前值的通信。

[source,json]
----
{
    "setbits":{
        "addr":9,
        "mask":[1,2],
         "value":7

    }
}
----
<1> addr为写操作的目标寄存器地址，必要参数，类型int，寄存器地址范围0~62 超出范围返回错误
<2> mask为掩码，必要参数，例如 "mask":[5,3] 表示只写 bit5~bit3 ，其他位保持不变，写入内容为value的值，数组个数必须为两个，左边的必须比右边的大
<3> value为写入的值目标比特的值，范围还是0~0xFFFF， 但是会以mask位截断高位。例如mask还是上面的[5,3]，当"value":12 时，12的二进制值为0b1100
如下表所示，bit6被切断忽略

[width="15%"]
|=======
|Bit15 |Bit14 |Bit13 |Bit12 |Bit11 |Bit10 |Bit 9 |Bit 8 |Bit 7 |Bit 6 |Bit 5 |Bit 4 |Bit 3 |Bit 2 |Bit 1 |Bit 0 
|0     |0     |0     |0     |0     |0     |0     |0     |0     |0     |1     |1     |1     |0     |0     |0     
|      |      |      |      |      |      |      |      |      |x     |1     |0     |0     |      |      |      
|=======
